#!/bin/bash

brown='\033[38;5;130m'
white='\033[0m'

if [ "$1" = "--version" ]; then
    echo "Version 1.1.0"
elif [ "$1" = "-v" ]; then
    echo "Version 1.1.0"
fi

echo -e "                codddddddddddolc"
echo -e "          lodk0KXXNNNNNNNWWWWWWWWX0koc"
echo -e "        oO0OO${brown}Okxddooolooddddxk0KN${white}WWWWWKkl"
echo -e "       kKOxl${brown};''';::cccllllolllc::;ok${white}XWWWWd"
echo -e "       NKx${brown},:.':cloodxxkdodlcc::l;....${white}xKWK"
echo -e "       XWOdcl${brown}::;;;;;:;;:lcllodxxxxxd${white}llOXKocclxkkdc"
echo -e "       NWWWXOkdooodddddoooddddddddkO0K00KdoolccoOKo"
echo -e "       XWWWWWWWWNXK00OOOOOO0000KKK0OOO0KXo     \#XKc"
echo -e "        WWWWWWWWWWWWWWWWNNNNXXXK00OOOO0KXx      xNO"
echo -e "        WWWWWWWWWWWWWWWWWNNNXXKK00OOO00KKK0kxxkKNO"
echo -e "         WWWWWWWWWWWWWWWNNNNXXKK000O00KKKKXXkkco/"
echo -e "         WWWWWWWWWWWWWWWNNNXXXK000000KKKKK"
echo -e "          WWWWWWWWWWWWWNNNXXXKKK000KKK0KK"
echo -e "           WWWWWWWWWWWNNNNXXXKKKKKKXXXXX"
echo -e "            WWWWWWWWWNNNNNXXXKKKKKXXXXX"
echo -e "             WWWWWWWNNNNNXXXXXXK0KKXXX"
echo -e "              WWWWWWNNNNNNXXKKKKXXXXX"
echo -e "               NNWWWWWNNNNNNNNNNNNNN"